# Generated by Django 5.1.3 on 2024-12-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='bulk_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
